### ISSUE TITLE
Server not working after Dolphin restart?

### ISSUE THREAD

**Issue by FunctionPoint** [rko281/Seaside#1]
(PS Don't know why the font is so big in the start of this issue, sorry :)
First of all, thanks for this port, I'm getting my program up and running in D7.1 again!
.
So to test, I first execute these 2 commands:
1 - (WASwazooAdaptor port: 8080) 	codec: (GRCodec forEncoding: 'utf-8'); start.
2 - ShellLibrary default shellOpen: 'http://localhost:8080/seaside'
And the browser comes up nicely with Seaside 3.2. Jay!
.
Then I exit Dolphin saving the image and restart it.
Now line 2 above gives the error in 3 browsers "localhost refused to connect".
Inspecting "WAServerManager default" indicates that it should be running.
.
Executing line 1 again, creates a second adaptor on the same port.
Now 1 is running, and one is not running. 
The error message in the browser is still: "localhost refused to connect"
.
When I increase the port number from 8080 to 8081,
I can execute lines 1 and 2 one again, and everything works fine on the new port.
But "WAServerManager default" now shows the old adaptors are still there.
.
The workaround I found is to forcibly remove all adaptor and server site instances (once).
Then execute line 1 and 2. (Everyting works fine the first time again).
After restarting Dolphin I can execute this to make it work again: 
"WAServerManager default adaptors first restart"
.
---
Soo, new adapators should probably not be created on the same port.
And maybe a restart of adaptors needs to be built in when starting up Dolphin.
.
Or am I missing something?

**Comment by rko281** [comment]
Thanks for the detailed info.

WAServerManager hooks into the image's shutdown and startup events via GRDolphinPlatform>>addToShutDownList: and addToStartUpList:. The issue looks to be that Pharo triggers the shutdown and startup events before and after the snapshot whereas Dolphin has additional (separate) events for pre- and post-image snapshot. Thus WAServerManager isn't informed when the image is being saved and so doesn't first stop the server.

I'll push a fix to Grease to address this.
